### ISSUE TITLE
name_attr can no longer be used (incl. workaround)

### ISSUE THREAD

**Issue by dan-s-github** [spacerokk/bar-card#1]
Thank you for maintaining this card for the community, as I had an issue after migrating I wanted to post it also here including the workaround I found as I might help others facing the same issue.

The unmaintained bar-card allowed to use name_attr to specify an attribute as name of the display entity, this no longer works and I assume this is related to the removed functionality of an upstream dependency (just guessing here).

![Image](https://github.com/user-attachments/assets/3d0f634a-7e1e-437c-9a74-c5d2a2f19808)

```
    entities:
      - entity: sensor.weatherflow_forecast_0
        name_attr: time
      - entity: sensor.weatherflow_forecast_1
        name_attr: time
      - entity: sensor.weatherflow_forecast_2
        name_attr: time
      - entity: sensor.weatherflow_forecast_3
        name_attr: time
      - entity: sensor.weatherflow_forecast_4
        name_attr: time
      - entity: sensor.weatherflow_forecast_5
        name_attr: time
      - entity: sensor.weatherflow_forecast_6
        name_attr: time
      - entity: sensor.weatherflow_forecast_7
        name_attr: time
```

as this no longer works I had to wrap the bar-card into `custom:config-template-card`

![Image](https://github.com/user-attachments/assets/7f9daf92-c355-407d-90ef-64d5c4d852e4)

```
   ...              
   - type: custom:config-template-card
      entities:
        - sensor.weatherflow_forecast_0
        - sensor.weatherflow_forecast_1
        - sensor.weatherflow_forecast_2
        - sensor.weatherflow_forecast_3
        - sensor.weatherflow_forecast_4
        - sensor.weatherflow_forecast_5
        - sensor.weatherflow_forecast_6
        - sensor.weatherflow_forecast_7
      card:
         type: custom:bar-card
         ....
         entities:
            - entity: sensor.weatherflow_forecast_0
              name: >-
                ${states['sensor.weatherflow_forecast_0'].attributes.time}
            - entity: sensor.weatherflow_forecast_1
              name: >-
                ${states['sensor.weatherflow_forecast_1'].attributes.time}
            - entity: sensor.weatherflow_forecast_2
              name: >-
                ${states['sensor.weatherflow_forecast_2'].attributes.time}
            - entity: sensor.weatherflow_forecast_3
              name: >-
                ${states['sensor.weatherflow_forecast_3'].attributes.time}
            - entity: sensor.weatherflow_forecast_4
              name: >-
                ${states['sensor.weatherflow_forecast_4'].attributes.time}
            - entity: sensor.weatherflow_forecast_5
              name: >-
                ${states['sensor.weatherflow_forecast_5'].attributes.time}
            - entity: sensor.weatherflow_forecast_6
              name: >-
                ${states['sensor.weatherflow_forecast_6'].attributes.time}
            - entity: sensor.weatherflow_forecast_7
              name: >-
                ${states['sensor.weatherflow_forecast_7'].attributes.time}

```
