### ISSUE TITLE
Add text under the last bar

### ISSUE THREAD

**Issue by Hufenbacke** [spacerokk/bar-card#3]
Hey bro,

I created a card thanks to your custom card. I was able to display what I wanted.
But now I have a small problem. My severity list has 6 values that each has a different color.
I would like to add a description/a chart legend under the bar.
Soooooo, How do I add a text block under the last bar?

Thanks!

**Comment by spacerokk** [comment]
@Hufenbacke Can you post your yml? I'm not as familiar with the capabilities as the original developer, so I'm not sure how much help I can be, but I'll take a look!

**Comment by Hufenbacke** [comment]
@spacerokk Thanks for your help. Here it is:

```
type: custom:bar-card
title: Schadstoffe
max: 500
unit_of_measurement: AQI
height: 40
width: 80%
entities:
  - entity: sensor.particulate_matter_pm25
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
  - entity: sensor.particulate_matter_pm10
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
  - entity: sensor.carbon_monoxide_co
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
  - entity: sensor.nitrogen_dioxide_no2
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
  - entity: sensor.ozone_o3
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
  - entity: sensor.sulphur_dioxide_so2
    positions:
      icon: none
      name: outside
      value: inside
    severity:
      - color: green
        from: 0
        to: 50
      - color: yellow
        from: 51
        to: 100
      - color: orange
        from: 101
        to: 150
      - color: red
        from: 151
        to: 200
      - color: purple
        from: 201
        to: 300
      - color: "#420000"
        from: 300
        to: 500
```
